CREATE TABLE UTILISATEUR
(
	ID              INTEGER AUTO_INCREMENT,
    NOM             VARCHAR(100) NOT NULL,
	PRENOM          VARCHAR(100) NOT NULL,
	EMAIL           VARCHAR(50) NOT NULL,
    TELEPHONE       VARCHAR(50) NOT NULL,
    NUMERO_DE_RUE   INTEGER NOT NULL,
    ADRESSE         VARCHAR(250) NOT NULL,
    PRIMARY KEY (ID)
);

CREATE TABLE EMPLACEMENT
(
    ID INTEGER AUTO_INCREMENT,
    NUMERO INTEGER NOT NULL,
    NUMERO_DE_RUE INTEGER NOT NULL,
    ADRESSE VARCHAR(250) NOT NULL,
    PRIMARY KEY (ID)
);

CREATE TABLE MARCHE
(
    ID INTEGER AUTO_INCREMENT,
    NOM VARCHAR(200) NOT NULL,
    DATE_MARCHE DATE NOT NULL,
    DESCRIPTION VARCHAR (500),
    URL_IMAGE VARCHAR(200),
    PRIMARY KEY (ID)
);

CREATE TABLE RESERVATION
(
	ID                              INTEGER AUTO_INCREMENT,
    DATE_RESERVATION                DATE,
    NUMERO                          INTEGER,
    ID_UTILISATEUR                  INTEGER NOT NULL,
    ID_EMPLACEMENT                  INTEGER NOT NULL,
    ID_MARCHE                       INTEGER NOT NULL,
    PRIMARY KEY (ID),
    FOREIGN KEY (ID_UTILISATEUR) REFERENCES UTILISATEUR (ID),
    FOREIGN KEY (ID_EMPLACEMENT) REFERENCES EMPLACEMENT(ID),
    FOREIGN KEY (ID_MARCHE) REFERENCES MARCHE(ID)
);


CREATE TABLE EMPLACEMENT_MARCHE
(
    ID              INTEGER AUTO_INCREMENT,
    ID_EMPLACEMENT  INTEGER NOT NULL,
    ID_MARCHE       INTEGER NOT NULL,
    PRIMARY KEY (ID),
    FOREIGN KEY (ID_EMPLACEMENT) REFERENCES EMPLACEMENT(ID),
    FOREIGN KEY (ID_MARCHE) REFERENCES MARCHE(ID)
);